import Head from "next/head";
import Image from "next/image";
import { Lato } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Logo from "./logo";

const font = Lato({ subsets: ["latin"], weight: "400" });

export default function Home() {
    function run() {
        const name = (document.getElementById("name") as HTMLInputElement).value;
        const requestOptions = {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                // Add any other headers as needed
            },
            body: JSON.stringify({ name: name }),
        };

        console.log(requestOptions);
        fetch(window.location.origin + "/api/createUser", requestOptions)
            .then((response) => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json(); // Assuming the response is in JSON format
            })
            .then((data) => {
                console.log(data);
                // Handle the data
                let uuid = data.result.replace(/[\r\n]/g, "");
                (document.getElementById("userImage") as HTMLImageElement).src = `./data/images/${uuid}.jpg`;
                (document.getElementById("displayName") as HTMLInputElement).textContent = name;
            })
            .catch((error) => {
                // Handle errors
                console.error("Fetch error:", error);
            });
    }

    function getUser() {
        const requestOptions = {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                // Add any other headers as needed
            },
            body: JSON.stringify({}),
        };

        console.log(requestOptions);
        fetch(window.location.origin + "/api/getUser", requestOptions)
            .then((response) => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json(); // Assuming the response is in JSON format
            })
            .then((data) => {
                console.log(data);
                // Handle the data
                let result = JSON.parse(data.result.replace(/[\r\n]/g, ""));
                (document.getElementById("userImage") as HTMLImageElement).src = `./data/images/${result.output}.jpg`;
                (document.getElementById("displayName") as HTMLInputElement).textContent = result.name;
            })
            .catch((error) => {
                // Handle errors
                console.error("Fetch error:", error);
            });
    }

    return (
        <>
            <Head>
                <title>Facial Tasker</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Logo className={`${styles.mainLogo}`} fillColor={"#101020"} gearColor={"#505070"}></Logo>
            <div className={`${styles.background}`}></div>
            <main className={`${font.className} ${styles.wrapper}`}>
                <p id="displayName"></p>
                <img id="userImage" className={`${styles.userImage}`} alt="" src=""></img>
                <div>
                    <label>Name</label>
                    <input id="name" placeholder="John Doe"></input>
                    <button onClick={run}>Create New User</button>
                </div>
                <div>
                    <button onClick={getUser}>Who Am I?</button>
                </div>
            </main>
        </>
    );
}
